# Generated by Django 5.2.17 on 2026-10-04 18:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('work_date', models.DateField()),
                ('body', models.TextField(max_length=10000)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('deletion_requested', 'deletion_requested'), ('deleted', 'deleted')], default='draft', max_length=30)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('lead_visible', 'Lead visible')], default='private', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('legal_hold', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.team')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('version', models.PositiveIntegerField()),
                ('body', models.TextField()),
                ('visibility', models.CharField(max_length=20)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='work_updates.workupdate')),
            ],
        ),
        migrations.AddIndex(
            model_name='workupdate',
            index=models.Index(fields=['organization', 'owner', 'status'], name='work_update_organiz_3ebce1_idx'),
        ),
        migrations.AddIndex(
            model_name='workupdate',
            index=models.Index(fields=['organization', 'team', 'visibility'], name='work_update_organiz_70de3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='workupdate',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['private', 'lead_visible'])), name='valid_update_visibility'),
        ),
        migrations.AddConstraint(
            model_name='workupdate',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published', 'deletion_requested', 'deleted'])), name='valid_update_status'),
        ),
        migrations.AddConstraint(
            model_name='updaterevision',
            constraint=models.UniqueConstraint(fields=('update', 'version'), name='unique_update_revision'),
        ),
    ]
