# Generated by Django 5.2.17 on 2026-10-05 11:57

from django.db import migrations, models
from importlib import import_module

def suspend(apps, schema_editor):
    if schema_editor.connection.vendor=='sqlite':
        import_module('apps.core.migrations.0003_integrity_guards').uninstall(apps,schema_editor)

def restore(apps, schema_editor):
    if schema_editor.connection.vendor=='sqlite':
        import_module('apps.core.migrations.0003_integrity_guards').install(apps,schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_production_guards'),
        ('work_updates', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(suspend,restore),
        migrations.AddField(
            model_name='workupdate',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(restore,suspend),
    ]
