# Generated by Django 5.2.17 on 2026-10-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersource',
            name='is_citation',
            field=models.BooleanField(default=True),
        ),
    ]
