# Generated by Django 5.2.17 on 2026-10-05 04:35

from django.db import migrations, models
from importlib import import_module

def suspend(apps, schema_editor):
    if schema_editor.connection.vendor=='sqlite':
        import_module('apps.core.migrations.0003_integrity_guards').uninstall(apps,schema_editor)

def restore(apps, schema_editor):
    if schema_editor.connection.vendor=='sqlite':
        import_module('apps.core.migrations.0003_integrity_guards').install(apps,schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_refresh_evidence_guards'),
        ('assistant', '0003_answersource_is_citation'),
    ]

    operations = [
        migrations.RunPython(suspend,restore),
        migrations.AddField(
            model_name='conversation',
            name='legal_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(restore,suspend),
    ]
