# Generated by Django 5.2.17 on 2026-10-04 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencyrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization'),
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='unique_idempotency_key'),
        ),
    ]
