# Generated by Django 5.2.17 on 2026-10-04 18:23

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('action', models.CharField(max_length=80)),
                ('target', models.CharField(max_length=100)),
                ('decision', models.CharField(max_length=15)),
                ('reason', models.CharField(max_length=60)),
                ('policy_version', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
