# Generated by Django 5.2.17 on 2026-10-04 18:23

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('classification', models.CharField(choices=[('project', 'Project'), ('restricted', 'Restricted')], default='restricted', max_length=20)),
                ('status', models.CharField(choices=[('processing', 'processing'), ('unpublished', 'unpublished'), ('published', 'published'), ('failed', 'failed'), ('quarantined', 'quarantined'), ('deletion_requested', 'deletion_requested'), ('deleted', 'deleted')], default='processing', max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('ever_published', models.BooleanField(default=False)),
                ('legal_hold', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('locator', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('version_no', models.PositiveIntegerField()),
                ('storage_key', models.CharField(max_length=100)),
                ('sha256', models.CharField(max_length=64)),
                ('mime', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=5)),
                ('byte_size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
