# Generated by Django 5.2.17 on 2026-10-04 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('identity', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization'),
        ),
        migrations.AddField(
            model_name='documentgrant',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentgrant',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentgrant',
            name='grantee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentgrant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.documentversion'),
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documentversion'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.documentversion'),
        ),
        migrations.AddConstraint(
            model_name='documentgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('document', 'grantee'), name='unique_unrevoked_grant'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_no'), name='unique_document_version'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('version', 'ordinal'), name='unique_chunk_ordinal'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'project', 'status'], name='documents_d_organiz_62ef25_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('classification__in', ['project', 'restricted'])), name='valid_document_classification'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['processing', 'unpublished', 'published', 'failed', 'quarantined', 'deletion_requested', 'deleted'])), name='valid_document_status'),
        ),
    ]
