# Generated by Django 5.2.17 on 2026-10-05 04:35

from django.db import migrations, models
from importlib import import_module

def suspend(apps, schema_editor):
    if schema_editor.connection.vendor=='sqlite':
        import_module('apps.core.migrations.0003_integrity_guards').uninstall(apps,schema_editor)

def restore(apps, schema_editor):
    if schema_editor.connection.vendor=='sqlite':
        import_module('apps.core.migrations.0003_integrity_guards').install(apps,schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_refresh_evidence_guards'),
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(suspend,restore),
        migrations.AddField(
            model_name='document',
            name='purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(restore,suspend),
    ]
